# Generated by Django 6.0.5 on 2026-07-16 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='article_link',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='video_link',
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='weightage',
            field=models.FloatField(default=0.0, help_text='Average marks weightage in GATE'),
        ),
        migrations.AddField(
            model_name='topic',
            name='importance_level',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='syllabus.branch'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='syllabus.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('branch', 'name')},
        ),
    ]
