# Generated by Django 6.0.5 on 2026-09-20 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_rename_title_topic_name_remove_topic_article_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='practice_completed',
            new_name='is_completed',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='theory_completed',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('branch', models.CharField(choices=[('CS', 'Computer Science & IT'), ('EC', 'Electronics & Communication'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('CH', 'Chemical Engineering'), ('IN', 'Instrumentation Engineering'), ('OT', 'Other')], max_length=2)),
                ('gate_target_year', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
